### ISSUE TITLE
two arrows showing up on playlist

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#353]
to recreate go to a playlist:

https://canvas.northwestern.edu/courses/47583/modules/items/921326

and note that there are two playlist arrows. 

![screen shot 2018-02-06 at 11 56 37 am](https://user-images.githubusercontent.com/4803230/35875450-eac5268c-0b34-11e8-8912-8128e66070b7.png)

**Comment by mbklein** [comment]
Fix pushed to nulib/staging at 1dbec6

**Comment by davidschober** [comment]
Done. Feel free to push @mbklein

**Comment by adamjarling** [comment]
@davidschober Verify?

**Comment by davidschober** [comment]
still seeing it.

**Comment by davidschober** [comment]
I'm still seeing this


![screen shot 2018-02-16 at 11 09 25 am](https://user-images.githubusercontent.com/4803230/36319874-ed75e16e-1309-11e8-84a6-5e2ede914185.png)

**Comment by adamjarling** [comment]
Can you shoot over the url?

**Comment by davidschober** [comment]
Sure. It looks like it's happening on all playlists

https://media.northwestern.edu/playlists/18

to recreate:

1. sign in
2. create a playlist
3. see playlist has two arrows.

**Comment by adamjarling** [comment]
Ok, I'll run this locally and see what's going on.

**Comment by adamjarling** [comment]
@davidschober @mbklein From the git commit history, looks like the https://github.com/nulib/avalon/commit/1dbec62e7d6c48bf9bf5ed3788f820d1c897af18 never made it to `aws-deploy-prod`?

**Comment by adamjarling** [comment]
There are some other UI items I'm cleaning up while in the code though...

**Comment by carrickr** [comment]
@davidschober Deployed to prod, not seeing two errors here:

https://media.northwestern.edu/playlists/95

**Comment by davidschober** [comment]
done
